from __future__ import annotations

from enum import Enum


class TimeOfDay(str, Enum):
    MORNING = "MORNING"
    DAY = "DAY"
    EVENING = "EVENING"
    NIGHT = "NIGHT"


class SymptomType(str, Enum):
    HEADACHE = "HEADACHE"
    MIGRAINE = "MIGRAINE"
    DIZZINESS = "DIZZINESS"
    WEAKNESS = "WEAKNESS"
    FATIGUE = "FATIGUE"
    JOINT_PAIN = "JOINT_PAIN"
    BACK_PAIN = "BACK_PAIN"
    HEART_PALPITATION = "HEART_PALPITATION"
    PRESSURE_SPIKE = "PRESSURE_SPIKE"
    LOW_PRESSURE = "LOW_PRESSURE"
    IRRITABILITY = "IRRITABILITY"
    ANXIETY = "ANXIETY"
    INSOMNIA = "INSOMNIA"
    DROWSINESS = "DROWSINESS"
    NAUSEA = "NAUSEA"
    BREATHING_DISCOMFORT = "BREATHING_DISCOMFORT"


class RiskReason(str, Enum):
    PRESSURE_DROP = "PRESSURE_DROP"
    PRESSURE_RISE = "PRESSURE_RISE"
    PRESSURE_SWING = "PRESSURE_SWING"

    TEMPERATURE_DROP = "TEMPERATURE_DROP"
    TEMPERATURE_RISE = "TEMPERATURE_RISE"
    TEMPERATURE_SWING = "TEMPERATURE_SWING"

    HIGH_HUMIDITY = "HIGH_HUMIDITY"
    LOW_HUMIDITY = "LOW_HUMIDITY"

    STRONG_WIND = "STRONG_WIND"
    PRECIPITATION = "PRECIPITATION"
    THUNDERSTORM = "THUNDERSTORM"

    GEOMAGNETIC_STORM = "GEOMAGNETIC_STORM"

    LOW_SUNLIGHT = "LOW_SUNLIGHT"
    HEAT_STRESS = "HEAT_STRESS"
    COLD_STRESS = "COLD_STRESS"

    HIGH_POLLEN = "HIGH_POLLEN"

class RecommendationType(str, Enum):
    DRINK_WATER = "DRINK_WATER"
    REDUCE_PHYSICAL_ACTIVITY = "REDUCE_PHYSICAL_ACTIVITY"
    AVOID_STRESS = "AVOID_STRESS"
    REST_MORE = "REST_MORE"
    SLEEP_EARLIER = "SLEEP_EARLIER"

    MONITOR_BLOOD_PRESSURE = "MONITOR_BLOOD_PRESSURE"
    AVOID_OVERHEATING = "AVOID_OVERHEATING"
    KEEP_WARM = "KEEP_WARM"
    VENTILATE_ROOM = "VENTILATE_ROOM"

    PREPARE_MEDICATION_BY_DOCTOR = "PREPARE_MEDICATION_BY_DOCTOR"
    AVOID_LONG_WALKS = "AVOID_LONG_WALKS"
    LIMIT_CAFFEINE = "LIMIT_CAFFEINE"
    PROTECT_FROM_WIND = "PROTECT_FROM_WIND"
    CHECK_POLLEN_EXPOSURE = "CHECK_POLLEN_EXPOSURE"
    USE_BREATHING_PRACTICES = "USE_BREATHING_PRACTICES"
    
class UserHealthCategory(str, Enum):
    HYPOTONIC = "HYPOTONIC"
    HYPERTONIC = "HYPERTONIC"
    JOINT_DISEASE = "JOINT_DISEASE"
    MIGRAINE = "MIGRAINE"
    GENERAL = "GENERAL"