from __future__ import annotations

from enum import Enum


class TimeOfDay(str, Enum):
    MORNING = "MORNING"
    DAY = "DAY"
    EVENING = "EVENING"
    NIGHT = "NIGHT"


class SymptomType(str, Enum):
    HEADACHE = "HEADACHE"
    MIGRAINE = "MIGRAINE"
    DIZZINESS = "DIZZINESS"
    WEAKNESS = "WEAKNESS"
    FATIGUE = "FATIGUE"
    JOINT_PAIN = "JOINT_PAIN"
    BACK_PAIN = "BACK_PAIN"
    HEART_PALPITATION = "HEART_PALPITATION"
    PRESSURE_SPIKE = "PRESSURE_SPIKE"
    LOW_PRESSURE = "LOW_PRESSURE"
    IRRITABILITY = "IRRITABILITY"
    ANXIETY = "ANXIETY"
    INSOMNIA = "INSOMNIA"
    DROWSINESS = "DROWSINESS"
    NAUSEA = "NAUSEA"
    BREATHING_DISCOMFORT = "BREATHING_DISCOMFORT"


class RiskReason(str, Enum):
    PRESSURE_DROP = "PRESSURE_DROP"
    PRESSURE_RISE = "PRESSURE_RISE"
    PRESSURE_SWING = "PRESSURE_SWING"

    TEMPERATURE_DROP = "TEMPERATURE_DROP"
    TEMPERATURE_RISE = "TEMPERATURE_RISE"
    TEMPERATURE_SWING = "TEMPERATURE_SWING"

    HIGH_HUMIDITY = "HIGH_HUMIDITY"
    LOW_HUMIDITY = "LOW_HUMIDITY"

    STRONG_WIND = "STRONG_WIND"
    PRECIPITATION = "PRECIPITATION"
    THUNDERSTORM = "THUNDERSTORM"

    GEOMAGNETIC_STORM = "GEOMAGNETIC_STORM"

    LOW_SUNLIGHT = "LOW_SUNLIGHT"
    HEAT_STRESS = "HEAT_STRESS"
    COLD_STRESS = "COLD_STRESS"

    HIGH_POLLEN = "HIGH_POLLEN"